// data.tsx
export const users = [
    {
      Platform: "Codeforces",
      ContestId: "110398",
      ContestName: "Div-2",
      Start_time: "21:05",
      Date: "12-01-23",
      Duration_time: "2:00",
      Urhl: "https://Codeforces.com/contests",
    },
    {
        Platform:"CodeChef",
        ContestId: "110399",
        ContestName: "Starters 122",
        Start_time: "21:05",
        Date:"14-01-23",
        Duration_time: "2:00",
        Urhl:"https://www.codechef.com/contests",
      },
      {
        Platform:"CodeChef",
        ContestId: "110400",
        ContestName: "Starters 105",
        Start_time: "21:05",
        Date:"15-01-23",
        Duration_time: "2:00",
        Urhl:"https://www.codechef.com/contests",
      },
      {
        Platform:"Codeforces",
        ContestId: "110401",
        ContestName: "Div-2",
        Start_time: "21:05",
        Date:"17-01-23",
        Duration_time: "2:00",
        Urhl:"https://Codeforces.com/contests",
      },
      {
        Platform:"Codeforces",
        ContestId: "110402",
        ContestName: "Div-4",
        Start_time: "21:05",
        Date:"19-01-23",
        Duration_time: "2:00",
        Urhl:"https://Codeforces.com/contests",
      },
      {
        Platform:"CodeChef",
        ContestId: "110403",
        ContestName: "Starters 120",
        Start_time: "21:05",
        Date:"20-01-23",
        Duration_time: "2:00",
        Urhl:"https://www.codechef.com/contests",
      },
      {
        Platform:"CodeChef",
        ContestId: "110404",
        ContestName: "Starters 122",
        Start_time: "21:05",
        Date:"21-01-23",
        Duration_time: "2:00",
        Urhl:"https://www.codechef.com/contests",
      },
  ];
  